name: contacts_bridge
description: A modern Flutter plugin for managing device contacts with support for Android, iOS, and macOS. Features comprehensive contact operations, group management, and permission handling.
version: 1.0.2
homepage: https://github.com/ahmtydn/contacts_bridge
repository: https://github.com/ahmtydn/contacts_bridge
documentation: https://github.com/ahmtydn/contacts_bridge/wiki
issue_tracker: https://github.com/ahmtydn/contacts_bridge/issues

topics:
  - contacts
  - flutter-plugin
  - address-book
  - cross-platform
  - native-integration

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  meta: ^1.9.1
  equatable: ^2.0.5
  collection: ^1.19.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ahmtydn.contacts_bridge
        pluginClass: ContactsBridgePlugin
      ios:
        pluginClass: ContactsBridgePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: ContactsBridgePlugin
        sharedDarwinSource: true

 